import React, { createContext, useContext, useState } from "react";

const LanguageContext = createContext(null);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState("en"); // Default to Hebrew

  const toggleLanguage = () => {
    setLanguage((prev) => (prev === "en" ? "he" : "en"));
  };

  const translations = {
    he: {
      heroTitle: "חליפות יוקרה מעוצבות",
      heroSubtitle:
        "גלה את הקולקציה האקסקלוסיבית שלנו של חליפות מעוצבות בקפידה, שם מלאכת יד מסורתית פוגשת עיצוב עכשווי. כל חליפה נתפרת לשלמות, מבטיחה התאמה מושלמת ותחכום חסר תחרות.",
      designButton: "עצב חליפה מותאמת",
      scrollDown: "גלול למטה",
      mostPopular: "הכי פופולרי",
      mostPopularSubtitle:
        "הבחירה המשובחת שלנו של חליפות שהפכו למועדפות על הלקוחות בזכות האיכות יוצאת הדופן והסגנון הנצחי שלהן.",
      orderSuitsTitle: "חליפות מהזמנות שלך",
      orderSuitsSubtitle:
        "גלריית חליפות מהזמנות - תוכל לעשות לייק לחליפות האהובות עליך",
      likeButton: "לייק",
      likedButton: "אהבתי",
      loadingSuits: "טוען חליפות...",
      noSuitsFound: "לא נמצאו חליפות מהזמנות",
      noSuitsMessage: "הזמן חליפה כדי לראות אותה כאן",
      stopRotation: "עצור רוטציה",
      startRotation: "התחל רוטציה",
      artOfTailoringText:
        "החייטים המומחים שלנו מביאים עשרות שנים של ניסיון לכל חליפה, משלבים טכניקות מסורתיות עם דיוק מודרני. כל בגד נוצר עם תשומת לב קפדנית לפרטים, מבחירת בדים יוקרתיים ועד הגימורים הנתפרים ביד.",
      ourProcess: "התהליך שלנו",
      ourCollections: "הקולקציות שלנו",
      collectionsSubtitle:
        "עיין בקולקציות המעוצבות בקפידה שלנו, שתוכננו לכל אירוע וסגנון אישי.",
      languageButton: "EN",
      // NavBar translations
      home: "בית",
      customSuit: "חליפה מותאמת",
      about: "אודות",
      contact: "צור קשר",
      sizeGuide: "מדריך מידות",
      support: "תמיכה",
      account: "חשבון",
      shoppingBag: "סל קניות",
      // About page translations
      returnToMain: "חזור לדף הראשי",
      ourHeritage: "המורשת שלנו",
      italianCraftsmanship: "מלאכת יד איטלקית מאז 1957",
      aboutParagraph1:
        "נוסד בשנת 1957, בית המלאכה האיטלקי שלנו לחליפות היה סמל לאלגנטיות נצחית ומלאכת יד יוצאת דופן במשך למעלה משישה עשורים. ממוקם בלב איטליה, אנו גאים לעצב ולחייט חליפות איכותיות המשלבות מסורת עם תחכום מודרני.",
      aboutParagraph2:
        "כל חליפה נוצרת בדיוק על ידי אומנים מיומנים המשתמשים בבדים האיטלקיים המשובחים ביותר, מבטיחה התאמה מושלמת ונוחות חסרת תחרות. בין אם אתם מחפשים חליפת עסקים קלאסית, טוקסידו אלגנטי, או יצירת מופת מותאמת אישית, הקולקציה שלנו מציעה מגוון רחב של עיצובים המתאימים לכל אירוע.",
      artOfTailoring: "אמנות החייטות",
      aboutParagraph3:
        "המחויבות שלנו למצוינות ותשומת הלב לפרטים הפכו אותנו לשם מהימן באופנת גברים, מושכים לקוחות מכל העולם. אנו מאמינים שחליפה מחויטת היטב היא יותר מאשר רק בגד - זה הצהרה של ביטחון, סגנון ומסורת.",
      aboutParagraph4:
        "כל בגד עובר דרך ידיהם של לפחות 16 אומנים מומחים, ממעצבי דפוסים ועד מומחי כפתורים. אנו שומרים על הטכניקות המסורתיות שהועברו מדור לדור, מבטיחים שכל תפר תורם הן למשיכה האסתטית והן לשלמות המבנית של היצירה הסופית.",
      aboutQuote:
        "בקרו אותנו וחוו את מהות החייטות האיטלקית, שם איכות פוגשת מורשת, וכל חליפה מספרת סיפור של מלאכת יד ומסורת.",
      // Contact page translations
      contactUs: "צור קשר",
      sendUsMessage: "שלח לנו הודעה",
      contactDescription:
        "נשמח לשמוע ממך. אנא מלא את הטופס למטה ונחזור אליך בהקדם האפשרי.",
      fullName: "שם מלא",
      emailAddress: "כתובת מייל",
      subject: "נושא",
      message: "הודעה",
      sendMessage: "שלח הודעה",
      contactInformation: "פרטי קשר",
      address: "כתובת",
      phone: "טלפון",
      email: "מייל",
      openingHours: "שעות פתיחה",
      returnToMainPage: "חזור לדף הראשי",
      // PolicySupport page translations
      policiesSupport: "מדיניות ותמיכה",
      ourPolicies: "המדיניות שלנו",
      policiesDescription:
        "ב-Italian Suits, אנו שואפים לספק שירות ותמיכה יוצאי דופן ללקוחותינו. למטה תמצאו מידע מפורט על המדיניות והשירותים שלנו.",
      shippingDelivery: "משלוחים ומסירה",
      shippingItem1: "הזמנות מעובדות תוך 1-3 ימי עסקים.",
      shippingItem2: "משלוח סטנדרטי לוקח 5-10 ימי עסקים; משלוח מהיר 2-5 ימים.",
      shippingItem3: "אנו מציעים משלוחים ברחבי העולם; זמני המסירה משתנים.",
      shippingItem4: "עמלות המשלוח מחושבות בקופה.",
      shippingItem5: 'מידע מעקב נשלח בדוא"ל לאחר המשלוח.',
      returnsExchanges: "החזרות והחלפות",
      returnsItem1: "החזרות מתקבלות תוך 14 יום אם לא נלבשו ולא שונו.",
      returnsItem2: "החלפות זמינות תוך 7 ימים להתאמות גודל/סגנון.",
      returnsItem3: "חליפות מותאמות אישית ופריטי סוף עונה אינם ניתנים להחזרה.",
      returnsItem4: "החזרים מונפקים תוך 7 ימי עסקים לאחר אישור ההחזרה.",
      sizingAssistance: "סיוע במידות",
      sizingItem1: "השתמש במדריך המידות המפורט שלנו להתאמה הטובה ביותר.",
      sizingItem2: "חליפות מותאמות אישית זמינות בהתבסס על מידות.",
      sizingItem3: "תמיכת צ'אט חי לעזרה במידות לפני ההזמנה.",
      customerSupport: "תמיכת לקוחות",
      supportItem1: 'דוא"ל: support@italiansuits.com',
      supportItem2: "טלפון: +39 123 456 7890",
      supportItem3: "צ'אט חי: זמין בימים א'-ו', 9:00 - 18:00 (CET).",
      supportItem4: "אנו מגיבים לשאילתות תוך 24 שעות.",
      privacyPolicy: "מדיניות פרטיות",
      privacyItem1: "אנו משתמשים בהצפנה מאובטחת להגנה על נתונים אישיים.",
      privacyItem2: "המידע שלך לעולם לא נמכר או משותף עם צדדים שלישיים.",
      privacyItem3: 'תוכל לבטל את הרשמתך לדוא"ל שיווקי בכל עת.',
      privacyItem4: "אנו עומדים ב-GDPR ובתקנות פרטיות אחרות.",
      bespokeService: "שירות מותאם אישית",
      bespokeDescription1:
        "שירות המותאם אישית שלנו מציע חוויה מותאמת אישית באמת. כל חליפה מותאמת אישית נוצרת לפי המידות וההעדפות המדויקות שלך, מבטיחה התאמה מושלמת וסגנון ייחודי המשקף את האישיות שלך.",
      bespokeDescription2:
        "תהליך המותאם אישית לוקח בדרך כלל 4-6 שבועות מהתייעצות ראשונית ועד למסירה סופית. במהלך הזמן הזה, החייטים המומחים שלנו יעבדו בקפידה ליצירת בגד באיכות יוצאת דופן.",
      careInstructions: "הוראות טיפול",
      careDescription1:
        "כדי לשמור על האיכות והעמידות של החליפה שלך, אנו ממליצים ניקוי יבש רק בעת הצורך, בדרך כלל 2-3 פעמים בשנה. בין הניקויים, השתמש במברשת רכה להסרת אבק וניקוי נקודתי לפי הצורך.",
      careDescription2:
        "תמיד תלה את החליפה שלך על מתלה עץ מתאים כדי לשמור על צורתה, והרשה לה לנוח לפחות 24 שעות בין לבישות כדי לאפשר לסיבים הטבעיים להתאושש.",
      warrantyInformation: "מידע על אחריות",
      warrantyDescription1:
        "כל החליפות שלנו מגיעות עם אחריות של שנה אחת כנגד פגמי ייצור. זה כולל בעיות עם תפירה, כפתורים ואיכות הבד בתנאי בלאי רגילים.",
      warrantyDescription2:
        "למשך 30 הימים הראשונים לאחר הרכישה, אנו מציעים גם שינויים קלים משלימים כדי להבטיח את שביעות הרצון המלאה שלך עם ההתאמה של הבגד שלך.",
      // IndexSizes page translations
      chooseMeasurementMethod: "בחר את שיטת המדידה שלך",
      measurementMethodSubtitle:
        "בחר את גישת המדידה שעובדת הכי טוב עבורך. כל שיטה מבטיחה התאמה מושלמת לחליפה המותאמת אישית שלך.",
      measureYourBody: "מדוד את הגוף שלך",
      customMeasurements: "מדידות מותאמות אישית",
      measureDescription: "קבל מדידות מדויקות להתאמה מושלמת",
      regularSizes: "מידות רגילות",
      chooseStandardSizes: "בחר ממידות סטנדרטיות",
      regularDescription: "מושלם אם אתה יודע את מידת החליפה הסטנדרטית שלך",
      getStarted: "התחל",
      // Shopping page translations
      premiumSuitCollection: "קולקציית חליפות פרימיום",
      shoppingSubtitle:
        "גלה את החליפות המעוצבות ביד שלנו המיועדות לג'נטלמן המודרני",
      forPayment: "לתשלום",
      availableSuits: "חליפות זמינות",
      qualityGrade: "דרגת איכות",
      newest: "החדש ביותר",
      priceLowToHigh: "מחיר: נמוך לגבוה",
      priceHighToLow: "מחיר: גבוה לנמוך",
      // Account page translations
      userProfile: "פרופיל משתמש",
      personalInformation: "מידע אישי",
      bodyMeasurements: "מדידות גוף",
      orderHistory: "היסטוריית הזמנות",
      firstName: "שם פרטי",
      lastName: "שם משפחה",
      phoneNumber: "מספר טלפון",
      deliveryAddress: "כתובת למשלוח",
      memberSince: "חבר מאז",
      notProvided: "לא סופק",
      missingPhoneNumber: "מספר טלפון חסר",
      missingAddress: "כתובת חסרה",
      edit: "ערוך",
      add: "הוסף",
      sizeProfiles: "פרופילי מידות",
      editMeasurements: "ערוך מדידות",
      recommendedSizes: "מידות מומלצות",
      jacketSize: "מידת ז'קט",
      pantsSize: "מידת מכנסיים",
      selectProfile: "בחר פרופיל:",
      deleteProfile: "מחק פרופיל",
      sortBy: "מיין לפי:",
      newestFirst: "החדש ביותר קודם",
      oldestFirst: "הישן ביותר קודם",
      totalOrders: 'סה"כ הזמנות',
      totalSpent: 'סה"כ הוצא',
      loadingOrders: "טוען הזמנות...",
      noOrdersFound:
        "לא נמצאו הזמנות. התחל לקנות כדי לראות את היסטוריית ההזמנות שלך כאן.",
      order: "הזמנה",
      estimatedDelivery: "משלוח משוער:",
      calculating: "מחשב...",
      viewAllSuits: "צפה בכל {count} החליפות",
      viewMoreDetails: "צפה בפרטים נוספים",
      standardSuit: "חליפה סטנדרטית",
      premiumSuit: "חליפה פרימיום",
      luxurySuit: "חליפה יוקרתית",
      customLuxurySuit: "חליפה יוקרתית מותאמת אישית",
      express: "אקספרס",
      pleaseLogIn: "אנא התחבר כדי לראות את פרטי החשבון שלך",
      // CheckoutModern page translations
      orderSummary: "סיכום הזמנה",
      showAsList: "הצג כרשימה",
      showAsCards: "הצג ככרטיסים",
      noImage: "אין תמונה",
      deliveryOptions: "אפשרויות משלוח",
      standardDelivery: "משלוח סטנדרטי",
      standardDeliveryTime: "3-5 ימי עסקים",
      expressDelivery: "משלוח מהיר",
      expressDeliveryTime: "1-2 ימי עסקים",
      sameDayDelivery: "משלוח באותו יום",
      sameDayDeliveryTime: "תוך 6 שעות",
      free: "חינם",
      sizeSelection: "בחירת מידה",
      tailoredFit: "התאמה מותאמת",
      standardSizes: "מידות סטנדרטיות",
      noSizeProfiles: "אין לך פרופילי מידות שמורים. צור אחד בפרופיל שלך.",
      jacketSizeLabel: "מידת ז'קט:",
      pantsSizeLabel: "מידת מכנסיים:",
      addressLabel: "כתובת:",
      phoneLabel: "טלפון:",
      missingAddressMessage:
        "כתובת חסרה, אנא הוסף את הכתובת שלך בהגדרות החשבון",
      missingPhoneMessage:
        "מספר טלפון חסר, אנא הוסף את מספר הטלפון שלך בהגדרות החשבון",
      editContactInformation: "ערוך פרטי קשר",
      paymentSummary: "סיכום תשלום",
      subtotal: "סיכום ביניים",
      shipping: "משלוח",
      total: 'סה"כ',
      securePaymentMessage:
        "תשלום מאובטח — הצפנת SSL 256-bit מגנה על הנתונים שלך",
      selectPaymentMethod: "בחר אמצעי תשלום",
      or: "או",
      regularPayment: "תשלום רגיל",
      pay: "שלם",
      weAcceptPayment: "אנו מקבלים כרטיסי אשראי מרכזיים ו-PayPal",
      // PaymentSuccess page translations
      paymentInformationNotFound: "מידע תשלום לא נמצא",
      returnToShoppingMessage: "אנא חזור לדף הקניות ונסה שוב",
      backToShopping: "חזור לקניות",
      paymentProcessed: "תשלום עובד",
      paymentSuccessful: "תשלום הצליח",
      paymentProcessedMessage: "התשלום שלך עובד בהצלחה",
      thankYouForPurchase: "תודה על הרכישה שלך",
      awaitingApproval: "ממתין לאישור",
      completed: "הושלם",
      orderBeingReviewed:
        'ההזמנה שלך נבדקת כעת ותאושר בקרוב. תקבל דוא"ל אישור ברגע שההזמנה שלך תאושר.',
      orderDetails: "פרטי הזמנה",
      orderId: "מספר הזמנה:",
      totalAmount: "סכום כולל:",
      shippingCost: "עלות משלוח:",
      shippingType: "סוג משלוח:",
      items: "פריטים:",
      suit: "חליפה",
      suits: "חליפות",
      processingOrderMessage:
        "אנו מעבדים את ההזמנה שלך ונודיע לך ברגע שהיא תאושר. זה בדרך כלל לוקח 1-2 ימי עסקים.",
      orderConfirmedMessage:
        "ההזמנה שלך אושרה ותישלח בהתאם לשיטת המשלוח שבחרת.",
      continueShopping: "המשך לקנות",
      viewOrders: "צפה בהזמנות",
      // Payed page translations
      yourOrder: "ההזמנה שלך",
      itemsInBag: "פריטים בסל שלך בשווי",
      shippingCostLabel: "עלות משלוח:",
      freeTracked: "חינם ומעקב (0€)",
      fastTracked: "מהיר ומעקב (+20€)",
      fastestTracked: "המהיר ביותר ומעקב (+35€)",
      selectSizeProfileType: "בחר סוג פרופיל מידה",
      regularProfile: "פרופיל רגיל",
      sizeTable: "טבלת מידות",
      selectAtLeastOneSuit: "אנא בחר לפחות חליפה אחת לפני המשך לתשלום",
      completeContactInfo: "אנא השלם את פרטי הקשר שלך לפני המשך לתשלום",
      continueToPayment: "המשך לתשלום",
      selectItems: "בחר פריטים",
      errorSavingOrder: "הייתה שגיאה בשמירת ההזמנה שלך. אנא פנה לתמיכה.",
      // PaymentDialog translations
      completeYourPayment: "השלם את התשלום שלך",
      paymentDetails: "פרטי תשלום",
      cancel: "ביטול",
      processing: "מעבד...",
      payAmount: "שלם {amount}€",
      failedToInitializePayment: "נכשל באתחול התשלום",
      paymentError: "אירעה שגיאה בעת עיבוד התשלום שלך.",
      // TakeSize3 page translations
      pleaseEnterProfileName: "אנא הכנס שם פרופיל",
      newProfileCreatedSuccessfully: "פרופיל חדש נוצר בהצלחה",
      failedToCreateProfile: "נכשל ביצירת פרופיל חדש",
      pleaseSelectProfileFirst: "אנא בחר פרופיל תחילה",
      measurementsSavedSuccessfully: "המדידות נשמרו בהצלחה",
      errorSavingMeasurements: "שגיאה בשמירת המדידות",
      createNewSizeProfile: "צור פרופיל מידה חדש",
      profileName: "שם פרופיל",
      create: "צור",
      default: "ברירת מחדל",
      enterMeasurementCm: 'הכנס מדידה (ס"מ)',
      // SuitDesign page translations
      classicSingle: "קלאסי יחיד",
      modernDouble: "מודרני כפול",
      contemporary: "עכשווי",
      traditional: "מסורתי",
      narrowLapel: "צווארון צר",
      wideLapel: "צווארון רחב",
      roundedLapel: "צווארון מעוגל",
      slim: "דק",
      standard: "סטנדרטי",
      wide: "רחב",
      extraWide: "רחב מאוד",
      classic: "קלאסי",
      modern: "מודרני",
      elegant: "אלגנטי",
      angledClassic: "קלאסי בזווית",
      angledModern: "מודרני בזווית",
      angledTraditional: "מסורתי בזווית",
      angledContemporary: "עכשווי בזווית",
      // PantsControls page translations
      regular: "רגיל",
      longRegular: "ארוך רגיל",
      longWide: "ארוך רחב",
      mediumWide: "בינוני רחב",
      noButton: "ללא כפתור",
      regularButton: "כפתור רגיל",
      middleButton: "כפתור אמצע",
      oneButton: "כפתור אחד",
      twoButtons: "שני כפתורים",
      noLoops: "ללא לולאות",
      oneLoop: "לולאה אחת",
      twoLoops: "שתי לולאות",
      noIron: "ללא גיהוץ",
      regularIron: "גיהוץ רגיל",
      oneIron: "גיהוץ אחד",
      oneIronTwoButtons: "גיהוץ אחד + שני כפתורים",
      wideIron: "גיהוץ רחב",
      save: "שמור",
      close: "סגור",
      noButtonSelected: "לא נבחר כפתור",
      allMeasurements: "כל המידות",
      // ActionButtons & StepNavigator translations
      start: "התחל",
      back: "חזור",
      nextStep: "השלב הבא",
      completeSuit: "השלם חליפה",
      saving: "שומר...",
      customSuitSavedSuccessfully: "החליפה המותאמת שלך נשמרה בהצלחה!",
      suitConfigurationExists: "תצורת החליפה הזו כבר קיימת!",
      errorSavingSuitConfiguration: "שגיאה בשמירת תצורת החליפה שלך",
      fabric: "בד",
      design: "עיצוב",
      details: "פרטים",
      fabricSelection: "בחירת בד",
      choosePremiumFabric: "בחר את הבד הפרימיום שלך",
      suitDesign: "עיצוב חליפה",
      selectStyleStructure: "בחר סגנון ומבנה",
      finishingDetails: "פרטי גימור",
      perfectPersonalTouch: "השלם את המגע האישי שלך",
      finalizeCreation: "סיים את היצירה שלך",
      stepLocked: "שלב נעול",
      completePreviousStep: "השלם את השלב הקודם כדי להמשיך",
      // FinishingDetails translations
      innerLining: "ריפוד פנימי",
      buttonStyle: "סגנון כפתור",
      buttonHoles: "חורי כפתורים",
      sleeveButtons: "כפתורי שרוולים",
      textInside: "טקסט פנימי",
      topCollarColor: "צבע צווארון עליון",
      noButtons: "ללא כפתורים",
      cleanMinimalLook: "מראה נקי ומינימלי",
      threeButtons: "3 כפתורים",
      classicThreeButtonStyle: "סגנון קלאסי של שלושה כפתורים",
      fourButtons: "4 כפתורים",
      modernFourButtonDesign: "עיצוב מודרני של ארבעה כפתורים",
      fiveButtons: "5 כפתורים",
      premiumFiveButtonFinish: "גימור פרימיום של חמישה כפתורים",
      classicBlackCollar: "צווארון שחור קלאסי",
      subtleLightGrey: "אפור בהיר עדין",
      sophisticatedDarkGrey: "אפור כהה מתוחכם",
      warmBeigeTone: "גוון בז' חם",
      boldRedAccent: "דגש אדום בולט",
      freshLightBlue: "כחול בהיר רענן",
      cleanWhiteFinish: "גימור לבן נקי",
      pantsCustomization: "התאמת מכנסיים",
      addFinishingTouches:
        "הוסף את המגעים הסופיים שהופכים את החליפה שלך לייחודית.",
      customizeButtonsLinings: "התאם אישית כפתורים, ריפודים ופרטים מיוחדים.",
      selectNumberOfButtons: "בחר את מספר הכפתורים לשרוולי השרוולים שלך",
      selectTopCollarColor: "בחר את הצבע לדגש צווארון העליון",
      chooseInnerLiningStyle: "בחר את סגנון הריפוד הפנימי שלך",
      selectButtonStyle: "בחר את סגנון הכפתור שלך",
      chooseButtonHoleColor: "בחר את צבע חורי הכפתורים",
      chooseHem: "בחר שוליים",
      pantsType: "סוג מכנסיים",
      chooseButtons: "בחר כפתורים",
      chooseIron: "בחר גיהוץ",
      chooseLoops: "בחר לולאות",
      allSuit: "כל החליפה",
      justUpper: "רק עליון",
      resetSelection: "איפוס בחירה",
      choosePocketSquare: "בחר כיס כיס",
      selectPocketSquareStyle: "בחר את סגנון כיס הכיס שלך",
      addTextInside: "הוסף טקסט פנימי",
      personalizeSuitWithCustomText: "התאם אישית את החליפה שלך עם טקסט מותאם",
      yourText: "הטקסט שלך",
      enterYourTextHere: "הכנס את הטקסט שלך כאן...",
      chooseTextColor: "בחר צבע טקסט",
      textSavedSuccessfully:
        "הטקסט נשמר בהצלחה! הוא יישמר עם החליפה כשתסיים ליצור אותה.",
      errorUpdatingTextSettings: "שגיאה בעדכון הגדרות הטקסט",
    },
    en: {
      heroTitle: "Timeless Elegance",
      heroSubtitle:
        "Discover our exclusive collection of meticulously crafted suits, where traditional craftsmanship meets contemporary design. Each piece is tailored to perfection, ensuring an impeccable fit and unparalleled sophistication.",
      designButton: "Start Designing Your Suit",
      scrollDown: "SCROLL DOWN",
      mostPopular: "Most Popular",
      mostPopularSubtitle:
        "Our finest selection of suits that have become customer favorites for their exceptional quality and timeless style.",
      orderSuitsTitle: "Your Order Suits",
      orderSuitsSubtitle:
        "Gallery of suits from your orders - you can like your favorite suits",
      likeButton: "Like",
      likedButton: "Liked",
      loadingSuits: "Loading suits...",
      noSuitsFound: "No suits found from orders",
      noSuitsMessage: "Order a suit to see it here",
      stopRotation: "Stop Rotation",
      startRotation: "Start Rotation",
      artOfTailoring: "The Art of Tailoring",
      artOfTailoringText:
        "Our master tailors bring decades of experience to every suit, combining traditional techniques with modern precision. Each garment is crafted with meticulous attention to detail, from the selection of premium fabrics to the final hand-stitched finishes.",
      ourProcess: "Our Process",
      ourCollections: "Our Collections",
      collectionsSubtitle:
        "Browse through our carefully curated collections designed for every occasion and personal style.",
      languageButton: "עב",
      // NavBar translations
      home: "Home",
      customSuit: "Custom Suit",
      about: "About",
      contact: "Contact",
      sizeGuide: "Size Guide",
      support: "Support",
      account: "Account",
      shoppingBag: "Shopping Bag",
      // About page translations
      returnToMain: "Return to Main Page",
      ourHeritage: "Our Heritage",
      italianCraftsmanship: "Italian Suit Craftsmanship Since 1957",
      aboutParagraph1:
        "Founded in 1957, our Italian suit atelier has been a symbol of timeless elegance and exceptional craftsmanship for over six decades. Located in the heart of Italy, we take pride in designing and tailoring high-quality suits that blend tradition with modern sophistication.",
      aboutParagraph2:
        "Each suit is crafted with precision by skilled artisans using the finest Italian fabrics, ensuring a perfect fit and unparalleled comfort. Whether you're looking for a classic business suit, a stylish tuxedo, or a custom-made masterpiece, our collection offers a wide range of designs to suit every occasion.",
      aboutParagraph3:
        "Our commitment to excellence and attention to detail have made us a trusted name in men's fashion, attracting clients from around the world. We believe that a well-tailored suit is more than just clothing—it's a statement of confidence, style, and tradition.",
      aboutParagraph4:
        "Each garment passes through the hands of at least 16 specialized artisans, from pattern makers to button specialists. We maintain the traditional techniques that have been passed down through generations, ensuring that every stitch contributes to both the aesthetic appeal and structural integrity of the final piece.",
      aboutQuote:
        "Visit us and experience the essence of Italian tailoring, where quality meets heritage, and every suit tells a story of craftsmanship and tradition.",
      // Contact page translations
      contactUs: "Contact Us",
      sendUsMessage: "Send Us a Message",
      contactDescription:
        "We'd love to hear from you. Please fill out the form below and we'll get back to you as soon as possible.",
      fullName: "Full Name",
      emailAddress: "Email Address",
      subject: "Subject",
      message: "Message",
      sendMessage: "Send Message",
      contactInformation: "Contact Information",
      address: "Address",
      phone: "Phone",
      email: "Email",
      openingHours: "Opening Hours",
      returnToMainPage: "Return to Main Page",
      // PolicySupport page translations
      policiesSupport: "Policies & Support",
      ourPolicies: "Our Policies",
      policiesDescription:
        "At Italian Suits, we strive to provide exceptional service and support to our customers. Below you'll find detailed information about our policies and services.",
      shippingDelivery: "Shipping & Delivery",
      shippingItem1: "Orders are processed within 1-3 business days.",
      shippingItem2:
        "Standard shipping takes 5-10 business days; expedited 2-5 days.",
      shippingItem3: "We offer worldwide shipping; delivery times vary.",
      shippingItem4: "Shipping fees are calculated at checkout.",
      shippingItem5: "Tracking information is sent via email once shipped.",
      returnsExchanges: "Returns & Exchanges",
      returnsItem1: "Returns accepted within 14 days if unworn and unaltered.",
      returnsItem2:
        "Exchanges available within 7 days for size/style adjustments.",
      returnsItem3: "Custom suits & clearance items are non-returnable.",
      returnsItem4:
        "Refunds issued within 7 business days after return approval.",
      sizingAssistance: "Sizing Assistance",
      sizingItem1: "Use our detailed size guide for best fit.",
      sizingItem2: "Custom-tailored suits available based on measurements.",
      sizingItem3: "Live chat support for sizing help before ordering.",
      customerSupport: "Customer Support",
      supportItem1: "Email: support@italiansuits.com",
      supportItem2: "Phone: +39 123 456 7890",
      supportItem3: "Live Chat: Available Mon-Fri, 9 AM - 6 PM (CET).",
      supportItem4: "We respond to inquiries within 24 hours.",
      privacyPolicy: "Privacy Policy",
      privacyItem1: "We use secure encryption to protect personal data.",
      privacyItem2:
        "Your information is never sold or shared with third parties.",
      privacyItem3: "You can opt out of marketing emails anytime.",
      privacyItem4: "We comply with GDPR and other privacy regulations.",
      bespokeService: "Bespoke Service",
      bespokeDescription1:
        "Our bespoke service offers a truly personalized experience. Each custom suit is crafted to your exact measurements and preferences, ensuring a perfect fit and unique style that reflects your personality.",
      bespokeDescription2:
        "The bespoke process typically takes 4-6 weeks from initial consultation to final delivery. During this time, our master tailors will work meticulously to create a garment of exceptional quality.",
      careInstructions: "Care Instructions",
      careDescription1:
        "To maintain the quality and longevity of your suit, we recommend dry cleaning only when necessary, typically 2-3 times per year. Between cleanings, use a soft brush to remove dust and spot clean as needed.",
      careDescription2:
        "Always hang your suit on a proper wooden hanger to maintain its shape, and allow it to rest for at least 24 hours between wearings to allow the natural fibers to recover.",
      warrantyInformation: "Warranty Information",
      warrantyDescription1:
        "All our suits come with a 1-year warranty against manufacturing defects. This includes issues with stitching, buttons, and fabric quality under normal wear conditions.",
      warrantyDescription2:
        "For the first 30 days after purchase, we also offer complimentary minor alterations to ensure your complete satisfaction with the fit of your garment.",
      // IndexSizes page translations
      chooseMeasurementMethod: "Choose Your Measurement Method",
      measurementMethodSubtitle:
        "Select the measurement approach that works best for you. Each method ensures a perfect fit for your custom suit.",
      measureYourBody: "Measure Your Body",
      customMeasurements: "Custom measurements",
      measureDescription: "Get precise measurements for a perfect fit",
      regularSizes: "Regular Sizes",
      chooseStandardSizes: "Choose from standard sizes",
      regularDescription: "Perfect if you know your standard suit size",
      getStarted: "Get Started",
      // Shopping page translations
      premiumSuitCollection: "Premium Suit Collection",
      shoppingSubtitle:
        "Discover our handcrafted suits designed for the modern gentleman",
      forPayment: "for payment",
      availableSuits: "Available Suits",
      qualityGrade: "Quality Grade",
      newest: "Newest",
      priceLowToHigh: "Price: Low to High",
      priceHighToLow: "Price: High to Low",
      // Account page translations
      userProfile: "User Profile",
      personalInformation: "Personal Information",
      bodyMeasurements: "Body Measurements",
      orderHistory: "Order History",
      firstName: "First Name",
      lastName: "Last Name",
      phoneNumber: "Phone Number",
      deliveryAddress: "Delivery Address",
      memberSince: "Member Since",
      notProvided: "Not provided",
      missingPhoneNumber: "Missing phone number",
      missingAddress: "Missing address",
      edit: "Edit",
      add: "Add",
      sizeProfiles: "Size Profiles",
      editMeasurements: "Edit Measurements",
      recommendedSizes: "Recommended Sizes",
      jacketSize: "Jacket Size",
      pantsSize: "Pants Size",
      selectProfile: "Select Profile:",
      deleteProfile: "Delete Profile",
      sortBy: "Sort by:",
      newestFirst: "Newest First",
      oldestFirst: "Oldest First",
      totalOrders: "Total Orders",
      totalSpent: "Total Spent",
      loadingOrders: "Loading orders...",
      noOrdersFound:
        "No orders found. Start shopping to see your order history here.",
      order: "Order",
      estimatedDelivery: "Estimated Delivery:",
      calculating: "Calculating...",
      viewAllSuits: "View all {count} suits",
      viewMoreDetails: "View More Details",
      standardSuit: "Standard Suit",
      premiumSuit: "Premium Suit",
      luxurySuit: "Luxury Suit",
      customLuxurySuit: "Custom Luxury Suit",
      express: "Express",
      pleaseLogIn: "Please log in to view your account details",
      // CheckoutModern page translations
      orderSummary: "Order Summary",
      showAsList: "Show as List",
      showAsCards: "Show as Cards",
      noImage: "No image",
      deliveryOptions: "Delivery Options",
      standardDelivery: "Standard Delivery",
      standardDeliveryTime: "3-5 business days",
      expressDelivery: "Express Delivery",
      expressDeliveryTime: "1-2 business days",
      sameDayDelivery: "Same Day Delivery",
      sameDayDeliveryTime: "Within 6 hours",
      free: "Free",
      sizeSelection: "Size Selection",
      tailoredFit: "Tailored Fit",
      standardSizes: "Standard Sizes",
      noSizeProfiles:
        "You don't have any saved size profiles. Create one in your profile.",
      jacketSizeLabel: "Jacket Size:",
      pantsSizeLabel: "Pants Size:",
      addressLabel: "Address:",
      phoneLabel: "Phone:",
      missingAddressMessage:
        "Missing address, please add your address in your account settings",
      missingPhoneMessage:
        "Missing phone number, please add your phone in your account settings",
      editContactInformation: "Edit Contact Information",
      paymentSummary: "Payment Summary",
      subtotal: "Subtotal",
      shipping: "Shipping",
      total: "Total",
      securePaymentMessage:
        "Secure Payment — 256-bit SSL encryption protects your data",
      selectPaymentMethod: "Select Payment Method",
      or: "or",
      regularPayment: "Regular Payment",
      pay: "Pay",
      weAcceptPayment: "We accept major credit cards and PayPal",
      // PaymentSuccess page translations
      paymentInformationNotFound: "Payment Information Not Found",
      returnToShoppingMessage:
        "Please return to the shopping page and try again",
      backToShopping: "Back to Shopping",
      paymentProcessed: "Payment Processed",
      paymentSuccessful: "Payment Successful",
      paymentProcessedMessage: "Your payment has been processed successfully",
      thankYouForPurchase: "Thank you for your purchase",
      awaitingApproval: "Awaiting Approval",
      completed: "Completed",
      orderBeingReviewed:
        "Your order is currently being reviewed and will be approved shortly. You will receive a confirmation email once your order is approved.",
      orderDetails: "Order Details",
      orderId: "Order ID:",
      totalAmount: "Total Amount:",
      shippingCost: "Shipping Cost:",
      shippingType: "Shipping Type:",
      items: "Items:",
      suit: "suit",
      suits: "suits",
      processingOrderMessage:
        "We're processing your order and will notify you once it's approved. This usually takes 1-2 business days.",
      orderConfirmedMessage:
        "Your order has been confirmed and will be shipped according to your selected shipping method.",
      continueShopping: "Continue Shopping",
      viewOrders: "View Orders",
      // Payed page translations
      yourOrder: "Your Order",
      itemsInBag: "Item/s in your Bag for a value of",
      shippingCostLabel: "Shipping cost:",
      freeTracked: "Free & tracked (0€)",
      fastTracked: "Fast & tracked (+20€)",
      fastestTracked: "Fastest & tracked (+35€)",
      selectSizeProfileType: "Select Size Profile Type",
      regularProfile: "Regular Profile",
      sizeTable: "Size Table",
      selectAtLeastOneSuit:
        "Please select at least one suit before proceeding to payment",
      completeContactInfo:
        "Please complete your contact information before proceeding to payment",
      continueToPayment: "Continue to Payment",
      selectItems: "Select Items",
      errorSavingOrder:
        "There was an error saving your order. Please contact support.",
      // PaymentDialog translations
      completeYourPayment: "Complete Your Payment",
      paymentDetails: "Payment Details",
      cancel: "Cancel",
      processing: "Processing...",
      payAmount: "Pay {amount}€",
      failedToInitializePayment: "Failed to initialize payment",
      paymentError: "An error occurred while processing your payment.",
      // TakeSize3 page translations
      pleaseEnterProfileName: "Please enter a profile name",
      newProfileCreatedSuccessfully: "New profile created successfully",
      failedToCreateProfile: "Failed to create new profile",
      pleaseSelectProfileFirst: "Please select a profile first",
      measurementsSavedSuccessfully: "Measurements saved successfully",
      errorSavingMeasurements: "Error saving measurements",
      createNewSizeProfile: "Create New Size Profile",
      profileName: "Profile Name",
      create: "Create",
      default: "Default",
      enterMeasurementCm: "Enter measurement (cm)",
      // SuitDesign page translations
      classicSingle: "Classic Single",
      modernDouble: "Modern Double",
      contemporary: "Contemporary",
      traditional: "Traditional",
      narrowLapel: "Narrow Lapel",
      wideLapel: "Wide Lapel",
      roundedLapel: "Rounded Lapel",
      slim: "Slim",
      standard: "Standard",
      wide: "Wide",
      extraWide: "Extra Wide",
      classic: "Classic",
      modern: "Modern",
      elegant: "Elegant",
      angledClassic: "Angled Classic",
      angledModern: "Angled Modern",
      angledTraditional: "Angled Traditional",
      angledContemporary: "Angled Contemporary",
      // PantsControls page translations
      regular: "Regular",
      longRegular: "Long Regular",
      longWide: "Long Wide",
      mediumWide: "Medium Wide",
      noButton: "No Button",
      regularButton: "Regular Button",
      middleButton: "Middle Button",
      oneButton: "One Button",
      twoButtons: "Two Buttons",
      noLoops: "No Loops",
      oneLoop: "One Loop",
      twoLoops: "Two Loops",
      noIron: "No Iron",
      regularIron: "Regular Iron",
      oneIron: "One Iron",
      oneIronTwoButtons: "One Iron + Two Buttons",
      wideIron: "Wide Iron",
      save: "Save",
      close: "Close",
      noButtonSelected: "No button selected",
      allMeasurements: "All Measurements",
      // ActionButtons & StepNavigator translations
      start: "Start",
      back: "Back",
      nextStep: "Next Step",
      completeSuit: "Complete Suit",
      saving: "Saving...",
      customSuitSavedSuccessfully:
        "Your custom suit has been saved successfully!",
      suitConfigurationExists: "This suit configuration already exists!",
      errorSavingSuitConfiguration: "Error saving your suit configuration",
      fabric: "Fabric",
      design: "Design",
      details: "Details",
      fabricSelection: "Fabric Selection",
      choosePremiumFabric: "Choose your premium fabric",
      suitDesign: "Suit Design",
      selectStyleStructure: "Select style & structure",
      finishingDetails: "Finishing Details",
      perfectPersonalTouch: "Perfect your personal touch",
      finalizeCreation: "Finalize your creation",
      stepLocked: "Step Locked",
      completePreviousStep: "Complete the previous step to continue",
      // FinishingDetails translations
      innerLining: "Inner Lining",
      buttonStyle: "Button Style",
      buttonHoles: "Button Holes",
      sleeveButtons: "Sleeve Buttons",
      textInside: "Text Inside",
      topCollarColor: "Top Collar Color",
      noButtons: "No Buttons",
      cleanMinimalLook: "Clean, minimal look",
      threeButtons: "3 Buttons",
      classicThreeButtonStyle: "Classic three-button style",
      fourButtons: "4 Buttons",
      modernFourButtonDesign: "Modern four-button design",
      fiveButtons: "5 Buttons",
      premiumFiveButtonFinish: "Premium five-button finish",
      classicBlackCollar: "Classic black collar",
      subtleLightGrey: "Subtle light grey",
      sophisticatedDarkGrey: "Sophisticated dark grey",
      warmBeigeTone: "Warm beige tone",
      boldRedAccent: "Bold red accent",
      freshLightBlue: "Fresh light blue",
      cleanWhiteFinish: "Clean white finish",
      pantsCustomization: "Pants Customization",
      addFinishingTouches:
        "Add the finishing touches that make your suit uniquely yours.",
      customizeButtonsLinings:
        "Customize buttons, linings, and special details.",
      selectNumberOfButtons:
        "Select the number of buttons for your sleeve cuffs",
      selectTopCollarColor: "Select the color for your top collar accent",
      chooseInnerLiningStyle: "Choose your inner lining style",
      selectButtonStyle: "Select your button style",
      chooseButtonHoleColor: "Choose your button hole color",
      chooseHem: "Choose Hem",
      pantsType: "Pants Type",
      chooseButtons: "Choose Buttons",
      chooseIron: "Choose Iron",
      chooseLoops: "Choose Loops",
      allSuit: "All Suit",
      justUpper: "Just Upper",
      resetSelection: "Reset Selection",
      choosePocketSquare: "Choose Pocket Square",
      selectPocketSquareStyle: "Select your pocket square style",
      addTextInside: "Add Text Inside",
      personalizeSuitWithCustomText: "Personalize your suit with custom text",
      yourText: "Your Text",
      enterYourTextHere: "Enter your text here...",
      chooseTextColor: "Choose Text Color",
      textSavedSuccessfully:
        "Text saved successfully! It will be saved with the suit when you finish creating it.",
      errorUpdatingTextSettings: "Error updating text settings",
    },
  };

  const t = (key) => {
    const translation = translations[language][key];
    if (!translation) {
      console.warn(
        `Missing translation for key: ${key} in language: ${language}`
      );
    }
    return translation || key;
  };

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
